server:
  port: 8080
  context-path: /
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8079/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: proxy